version: '3.1'
volumes:
  pg_timeweb:
services:
  pg_db:
    image: 'postgres:latest'
    restart: always
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=hack
    ports:
      - 5455:5432